version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: wp     # Поставете го вашиот username
      POSTGRES_PASSWORD: wp123  # Поставете ја вашата лозинка
      POSTGRES_DB: music                # Име на базата
    ports:
      - "5432:5432"  # Мапирање на локален порт на портот на PostgreSQL во Docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
